function updateData()
    cd('C:\Users\brianbj\OneDrive - Syddansk Universitet\Samples\RhodamineB')
    specTools(pwd())
    cd('C:\Users\brianbj\OneDrive - Syddansk Universitet\Samples\Rhodamine6G')
    specTools(pwd())
    cd('C:\Users\brianbj\OneDrive - Syddansk Universitet\Samples\NileRed')
    specTools(pwd())
    cd('C:\Users\brianbj\OneDrive - Syddansk Universitet\Samples\NileRedAnalog1')
    specTools(pwd())
    cd('C:\Users\brianbj\OneDrive - Syddansk Universitet\Samples\NileRedAnalog2')
    specTools(pwd())
    cd('C:\Users\brianbj\OneDrive - Syddansk Universitet\Samples\NileRedAnalog3')
    specTools(pwd())
    cd('C:\Users\brianbj\OneDrive - Syddansk Universitet\Samples\NileRedAnalog4')
    specTools(pwd())
    cd('C:\Users\brianbj\OneDrive - Syddansk Universitet\Samples\NileRedAnalog5')
    specTools(pwd())
end